### ISSUE TITLE
Erro 127 ao rodar o docker

### ISSUE THREAD

**Issue by juniopereirab** [fga-eps-mds/2018.2-FGAPP-produto#23]
**Describe the bug**
Após dar `sudo make build` e `sudo make` no microsserviço, me deparo com o erro (código 127)

**To Reproduce**
1. Atualizei o repositório local dando `git pull`
2. Executei o comando `sudo make build`
3. Executei o comando `sudo make`
4. Deu erro ao fazer a operação

**Expected behavior**
Eu esperava que o servidor Django executasse normalmente

**Screenshots**
![image](https://user-images.githubusercontent.com/17153869/47932343-1f90e500-deb0-11e8-9f7a-9f84de1cd97d.png)

**Desktop:**
 - OS: Ubuntu 16.04

**Comment by andrelucax** [comment]
Percebi que ele nao conseguia abrir o run-django.sh que esta em uma pasta a frente..

consegui resolver o problema alterando em `docker-compose.yml` o comando para `command: bash -c "cd product_microservice && sh run-django.sh"`, nao sei se sera uma solucao temporaria, depois resolvemos com o devops

**Comment by juniopereirab** [comment]
Obrigado pela solução do meu problema, ele realmente estava chamando um arquivo no diretório errado do microsserviço.

**Comment by lucasca73** [comment]
Reabri o PR. O correto é configurar o dockerfile de desenvolvimento corretamente. Poderiam checar o PR, rodar e ver se esta tudo ok?

**Comment by juniopereirab** [comment]
@lucasca73 Agora está tudo certo! Obrigado pela ajuda.
